# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graderrequest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13graderrequest.proto\x12\x14GraderRequestPackage\"(\n\x04\x46ile\x12\x0e\n\x06\x66ileid\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"\n\n\x08noParams\"\x1c\n\x06Status\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x32]\n\x14GraderRequestService\x12\x45\n\tGradeFile\x12\x1a.GraderRequestPackage.File\x1a\x1c.GraderRequestPackage.StatusB\x11Z\x0f./graderrequestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'graderrequest_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\017./graderrequest'
  _globals['_FILE']._serialized_start=45
  _globals['_FILE']._serialized_end=85
  _globals['_NOPARAMS']._serialized_start=87
  _globals['_NOPARAMS']._serialized_end=97
  _globals['_STATUS']._serialized_start=99
  _globals['_STATUS']._serialized_end=127
  _globals['_GRADERREQUESTSERVICE']._serialized_start=129
  _globals['_GRADERREQUESTSERVICE']._serialized_end=222
# @@protoc_insertion_point(module_scope)
